/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmployeeProfileRouteImport } from './routes/employee.profile'
import { Route as EmployeeLeavesRouteImport } from './routes/employee.leaves'
import { Route as EmployeeDashboardRouteImport } from './routes/employee.dashboard'
import { Route as EmployeeAttendanceRouteImport } from './routes/employee.attendance'
import { Route as CandidateStatusRouteImport } from './routes/candidate.status'
import { Route as CandidateProfileRouteImport } from './routes/candidate.profile'
import { Route as CandidateOnboardingRouteImport } from './routes/candidate.onboarding'
import { Route as CandidateDocumentsRouteImport } from './routes/candidate.documents'
import { Route as CandidateDashboardRouteImport } from './routes/candidate.dashboard'
import { Route as CandidateChangePasswordRouteImport } from './routes/candidate.change-password'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminOrgStructureRouteImport } from './routes/admin.org-structure'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminLeavesRouteImport } from './routes/admin.leaves'
import { Route as AdminEmployeesRouteImport } from './routes/admin.employees'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminCreateEmployeeRouteImport } from './routes/admin.create-employee'
import { Route as AdminCreateCandidateRouteImport } from './routes/admin.create-candidate'
import { Route as AdminCandidatesRouteImport } from './routes/admin.candidates'
import { Route as AdminAttendanceRouteImport } from './routes/admin.attendance'
import { Route as AdminCandidatesIdRouteImport } from './routes/admin.candidates.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeProfileRoute = EmployeeProfileRouteImport.update({
  id: '/employee/profile',
  path: '/employee/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeLeavesRoute = EmployeeLeavesRouteImport.update({
  id: '/employee/leaves',
  path: '/employee/leaves',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeDashboardRoute = EmployeeDashboardRouteImport.update({
  id: '/employee/dashboard',
  path: '/employee/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeAttendanceRoute = EmployeeAttendanceRouteImport.update({
  id: '/employee/attendance',
  path: '/employee/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateStatusRoute = CandidateStatusRouteImport.update({
  id: '/candidate/status',
  path: '/candidate/status',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateProfileRoute = CandidateProfileRouteImport.update({
  id: '/candidate/profile',
  path: '/candidate/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateOnboardingRoute = CandidateOnboardingRouteImport.update({
  id: '/candidate/onboarding',
  path: '/candidate/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateDocumentsRoute = CandidateDocumentsRouteImport.update({
  id: '/candidate/documents',
  path: '/candidate/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateDashboardRoute = CandidateDashboardRouteImport.update({
  id: '/candidate/dashboard',
  path: '/candidate/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateChangePasswordRoute = CandidateChangePasswordRouteImport.update({
  id: '/candidate/change-password',
  path: '/candidate/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrgStructureRoute = AdminOrgStructureRouteImport.update({
  id: '/admin/org-structure',
  path: '/admin/org-structure',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLeavesRoute = AdminLeavesRouteImport.update({
  id: '/admin/leaves',
  path: '/admin/leaves',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEmployeesRoute = AdminEmployeesRouteImport.update({
  id: '/admin/employees',
  path: '/admin/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCreateEmployeeRoute = AdminCreateEmployeeRouteImport.update({
  id: '/admin/create-employee',
  path: '/admin/create-employee',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCreateCandidateRoute = AdminCreateCandidateRouteImport.update({
  id: '/admin/create-candidate',
  path: '/admin/create-candidate',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCandidatesRoute = AdminCandidatesRouteImport.update({
  id: '/admin/candidates',
  path: '/admin/candidates',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAttendanceRoute = AdminAttendanceRouteImport.update({
  id: '/admin/attendance',
  path: '/admin/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCandidatesIdRoute = AdminCandidatesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminCandidatesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/candidates': typeof AdminCandidatesRouteWithChildren
  '/admin/create-candidate': typeof AdminCreateCandidateRoute
  '/admin/create-employee': typeof AdminCreateEmployeeRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/leaves': typeof AdminLeavesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/org-structure': typeof AdminOrgStructureRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/candidate/change-password': typeof CandidateChangePasswordRoute
  '/candidate/dashboard': typeof CandidateDashboardRoute
  '/candidate/documents': typeof CandidateDocumentsRoute
  '/candidate/onboarding': typeof CandidateOnboardingRoute
  '/candidate/profile': typeof CandidateProfileRoute
  '/candidate/status': typeof CandidateStatusRoute
  '/employee/attendance': typeof EmployeeAttendanceRoute
  '/employee/dashboard': typeof EmployeeDashboardRoute
  '/employee/leaves': typeof EmployeeLeavesRoute
  '/employee/profile': typeof EmployeeProfileRoute
  '/admin/candidates/$id': typeof AdminCandidatesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/candidates': typeof AdminCandidatesRouteWithChildren
  '/admin/create-candidate': typeof AdminCreateCandidateRoute
  '/admin/create-employee': typeof AdminCreateEmployeeRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/leaves': typeof AdminLeavesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/org-structure': typeof AdminOrgStructureRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/candidate/change-password': typeof CandidateChangePasswordRoute
  '/candidate/dashboard': typeof CandidateDashboardRoute
  '/candidate/documents': typeof CandidateDocumentsRoute
  '/candidate/onboarding': typeof CandidateOnboardingRoute
  '/candidate/profile': typeof CandidateProfileRoute
  '/candidate/status': typeof CandidateStatusRoute
  '/employee/attendance': typeof EmployeeAttendanceRoute
  '/employee/dashboard': typeof EmployeeDashboardRoute
  '/employee/leaves': typeof EmployeeLeavesRoute
  '/employee/profile': typeof EmployeeProfileRoute
  '/admin/candidates/$id': typeof AdminCandidatesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/candidates': typeof AdminCandidatesRouteWithChildren
  '/admin/create-candidate': typeof AdminCreateCandidateRoute
  '/admin/create-employee': typeof AdminCreateEmployeeRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/employees': typeof AdminEmployeesRoute
  '/admin/leaves': typeof AdminLeavesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/org-structure': typeof AdminOrgStructureRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/candidate/change-password': typeof CandidateChangePasswordRoute
  '/candidate/dashboard': typeof CandidateDashboardRoute
  '/candidate/documents': typeof CandidateDocumentsRoute
  '/candidate/onboarding': typeof CandidateOnboardingRoute
  '/candidate/profile': typeof CandidateProfileRoute
  '/candidate/status': typeof CandidateStatusRoute
  '/employee/attendance': typeof EmployeeAttendanceRoute
  '/employee/dashboard': typeof EmployeeDashboardRoute
  '/employee/leaves': typeof EmployeeLeavesRoute
  '/employee/profile': typeof EmployeeProfileRoute
  '/admin/candidates/$id': typeof AdminCandidatesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/attendance'
    | '/admin/candidates'
    | '/admin/create-candidate'
    | '/admin/create-employee'
    | '/admin/dashboard'
    | '/admin/employees'
    | '/admin/leaves'
    | '/admin/login'
    | '/admin/org-structure'
    | '/admin/reports'
    | '/admin/settings'
    | '/candidate/change-password'
    | '/candidate/dashboard'
    | '/candidate/documents'
    | '/candidate/onboarding'
    | '/candidate/profile'
    | '/candidate/status'
    | '/employee/attendance'
    | '/employee/dashboard'
    | '/employee/leaves'
    | '/employee/profile'
    | '/admin/candidates/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/attendance'
    | '/admin/candidates'
    | '/admin/create-candidate'
    | '/admin/create-employee'
    | '/admin/dashboard'
    | '/admin/employees'
    | '/admin/leaves'
    | '/admin/login'
    | '/admin/org-structure'
    | '/admin/reports'
    | '/admin/settings'
    | '/candidate/change-password'
    | '/candidate/dashboard'
    | '/candidate/documents'
    | '/candidate/onboarding'
    | '/candidate/profile'
    | '/candidate/status'
    | '/employee/attendance'
    | '/employee/dashboard'
    | '/employee/leaves'
    | '/employee/profile'
    | '/admin/candidates/$id'
  id:
    | '__root__'
    | '/'
    | '/admin/attendance'
    | '/admin/candidates'
    | '/admin/create-candidate'
    | '/admin/create-employee'
    | '/admin/dashboard'
    | '/admin/employees'
    | '/admin/leaves'
    | '/admin/login'
    | '/admin/org-structure'
    | '/admin/reports'
    | '/admin/settings'
    | '/candidate/change-password'
    | '/candidate/dashboard'
    | '/candidate/documents'
    | '/candidate/onboarding'
    | '/candidate/profile'
    | '/candidate/status'
    | '/employee/attendance'
    | '/employee/dashboard'
    | '/employee/leaves'
    | '/employee/profile'
    | '/admin/candidates/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminAttendanceRoute: typeof AdminAttendanceRoute
  AdminCandidatesRoute: typeof AdminCandidatesRouteWithChildren
  AdminCreateCandidateRoute: typeof AdminCreateCandidateRoute
  AdminCreateEmployeeRoute: typeof AdminCreateEmployeeRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminEmployeesRoute: typeof AdminEmployeesRoute
  AdminLeavesRoute: typeof AdminLeavesRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminOrgStructureRoute: typeof AdminOrgStructureRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  CandidateChangePasswordRoute: typeof CandidateChangePasswordRoute
  CandidateDashboardRoute: typeof CandidateDashboardRoute
  CandidateDocumentsRoute: typeof CandidateDocumentsRoute
  CandidateOnboardingRoute: typeof CandidateOnboardingRoute
  CandidateProfileRoute: typeof CandidateProfileRoute
  CandidateStatusRoute: typeof CandidateStatusRoute
  EmployeeAttendanceRoute: typeof EmployeeAttendanceRoute
  EmployeeDashboardRoute: typeof EmployeeDashboardRoute
  EmployeeLeavesRoute: typeof EmployeeLeavesRoute
  EmployeeProfileRoute: typeof EmployeeProfileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee/profile': {
      id: '/employee/profile'
      path: '/employee/profile'
      fullPath: '/employee/profile'
      preLoaderRoute: typeof EmployeeProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee/leaves': {
      id: '/employee/leaves'
      path: '/employee/leaves'
      fullPath: '/employee/leaves'
      preLoaderRoute: typeof EmployeeLeavesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee/dashboard': {
      id: '/employee/dashboard'
      path: '/employee/dashboard'
      fullPath: '/employee/dashboard'
      preLoaderRoute: typeof EmployeeDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee/attendance': {
      id: '/employee/attendance'
      path: '/employee/attendance'
      fullPath: '/employee/attendance'
      preLoaderRoute: typeof EmployeeAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/status': {
      id: '/candidate/status'
      path: '/candidate/status'
      fullPath: '/candidate/status'
      preLoaderRoute: typeof CandidateStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/profile': {
      id: '/candidate/profile'
      path: '/candidate/profile'
      fullPath: '/candidate/profile'
      preLoaderRoute: typeof CandidateProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/onboarding': {
      id: '/candidate/onboarding'
      path: '/candidate/onboarding'
      fullPath: '/candidate/onboarding'
      preLoaderRoute: typeof CandidateOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/documents': {
      id: '/candidate/documents'
      path: '/candidate/documents'
      fullPath: '/candidate/documents'
      preLoaderRoute: typeof CandidateDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/dashboard': {
      id: '/candidate/dashboard'
      path: '/candidate/dashboard'
      fullPath: '/candidate/dashboard'
      preLoaderRoute: typeof CandidateDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/change-password': {
      id: '/candidate/change-password'
      path: '/candidate/change-password'
      fullPath: '/candidate/change-password'
      preLoaderRoute: typeof CandidateChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/org-structure': {
      id: '/admin/org-structure'
      path: '/admin/org-structure'
      fullPath: '/admin/org-structure'
      preLoaderRoute: typeof AdminOrgStructureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/leaves': {
      id: '/admin/leaves'
      path: '/admin/leaves'
      fullPath: '/admin/leaves'
      preLoaderRoute: typeof AdminLeavesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/employees': {
      id: '/admin/employees'
      path: '/admin/employees'
      fullPath: '/admin/employees'
      preLoaderRoute: typeof AdminEmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/create-employee': {
      id: '/admin/create-employee'
      path: '/admin/create-employee'
      fullPath: '/admin/create-employee'
      preLoaderRoute: typeof AdminCreateEmployeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/create-candidate': {
      id: '/admin/create-candidate'
      path: '/admin/create-candidate'
      fullPath: '/admin/create-candidate'
      preLoaderRoute: typeof AdminCreateCandidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/candidates': {
      id: '/admin/candidates'
      path: '/admin/candidates'
      fullPath: '/admin/candidates'
      preLoaderRoute: typeof AdminCandidatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/attendance': {
      id: '/admin/attendance'
      path: '/admin/attendance'
      fullPath: '/admin/attendance'
      preLoaderRoute: typeof AdminAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/candidates/$id': {
      id: '/admin/candidates/$id'
      path: '/$id'
      fullPath: '/admin/candidates/$id'
      preLoaderRoute: typeof AdminCandidatesIdRouteImport
      parentRoute: typeof AdminCandidatesRoute
    }
  }
}

interface AdminCandidatesRouteChildren {
  AdminCandidatesIdRoute: typeof AdminCandidatesIdRoute
}

const AdminCandidatesRouteChildren: AdminCandidatesRouteChildren = {
  AdminCandidatesIdRoute: AdminCandidatesIdRoute,
}

const AdminCandidatesRouteWithChildren = AdminCandidatesRoute._addFileChildren(
  AdminCandidatesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminAttendanceRoute: AdminAttendanceRoute,
  AdminCandidatesRoute: AdminCandidatesRouteWithChildren,
  AdminCreateCandidateRoute: AdminCreateCandidateRoute,
  AdminCreateEmployeeRoute: AdminCreateEmployeeRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminEmployeesRoute: AdminEmployeesRoute,
  AdminLeavesRoute: AdminLeavesRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminOrgStructureRoute: AdminOrgStructureRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  CandidateChangePasswordRoute: CandidateChangePasswordRoute,
  CandidateDashboardRoute: CandidateDashboardRoute,
  CandidateDocumentsRoute: CandidateDocumentsRoute,
  CandidateOnboardingRoute: CandidateOnboardingRoute,
  CandidateProfileRoute: CandidateProfileRoute,
  CandidateStatusRoute: CandidateStatusRoute,
  EmployeeAttendanceRoute: EmployeeAttendanceRoute,
  EmployeeDashboardRoute: EmployeeDashboardRoute,
  EmployeeLeavesRoute: EmployeeLeavesRoute,
  EmployeeProfileRoute: EmployeeProfileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
